### ISSUE TITLE
checklist of ppc64le

### ISSUE THREAD

**Issue by njzjz** [deepmd-kit-recipes/tensorflow-base-feedstock#1]
- [x]     {{ compiler('c') }} (no gcc 5.4!)
- [x]     {{ compiler('cxx') }} (no gcc 5.4!)
- [x] #3
- [x]     cython
- [x]     python
- [x]     pip
- [x]     setuptools (noarch)
- [x]     wheel >=0.35,<0.36 (noarch)
- [x]     unzip        # [not win]
- [x]     zip          # [not win] (conda-forge)
- [x]     cython
- [x]     absl-py (noarch)
- [x]     astunparse 1.6.3 (noarch)
- [x]     python-flatbuffers 1.12.* (noarch)
- [x]     gast 0.4.0 (noarch)
- [x]     google-pasta 0.2 (noarch)
- [x]     grpcio
- [x]     h5py >=3.1.0
- [x]     keras-preprocessing >=1.1.2 (noarch)
- [x]     numpy
- [x]     opt_einsum 3.3.0.* (noarch)
- [x]     protobuf >=3.9.2
- [x]     scipy
- [x]     six >=1.15.0 (noarch)
- [x]     typing_extensions >=3.7.4 (noarch)
- [x]     swig
- [x]     termcolor >=1.1.0
- [x]     wrapt >=1.11.2
- [x]     tensorboard >=2.5.0,<2.6 (noarch)
- [x]     tensorflow-estimator >=2.5.0,<2.6 (noarch)
- [x]     cudatoolkit {{ cuda_compiler_version }}* (only 11.0 avaiable; conda-forge has 11.2)
- [x]     cudnn {{ cudnn }}* (only 7.0; conda-forge has 11.0)
- [x]     cupti  # [not win] (consider skip)

**Comment by njzjz** [comment]
'
